### PR TITLE
Fix ConsensusParams

### PR DESCRIPTION
**Pull request by james-chf**

### CODE REVIEW

**Comment by james-chf** [comment]
@sug0

**Review by sug0 — APPROVED** [review]

**Review by batconjurer — COMMENTED** [review]
Generally fine with it, but I'm very unhappy about all of these warnings. Is there something we can do about it?

**Comment by sug0** [comment]
well, we would need to maintain a custom CI for this fork I guess... it's already a hassle maintaining a fork

**Comment by james-chf** [comment]
> Generally fine with it, but I'm very unhappy about all of these warnings. Is there something we can do about it?

I agree we should do this, at least simple jobs like `cargo test` and the like should pass. Ideally we should get all jobs working including the gaia e2e tests.

**Comment by james-chf** [comment]
Have opened https://github.com/anoma/namada/issues/537

**Review by batconjurer — APPROVED** [review]

**Pull request merged**
